### ISSUE TITLE
Handle missing parameters in ocrd-tool.json like empty array

### ISSUE THREAD

**Issue by kba** [OCR-D/core#160]
```yaml
 "tools": {
    "ocrd-xyz": {
    }
  }
```

should be equivalent to

```yaml
 "tools": {
    "ocrd-xyz": {
     "parameters": []
    }
  }
```
