### ISSUE TITLE
resmgr: strange datetime interpretation of name

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#867]
If I add an entry…
```yaml
ocrd-eynollah-segment:
  - url: https://qurator-data.de/eynollah/2022-04-05/models_eynollah_renamed.tar.gz
    name: 2022-04-05
    description: models for eynollah
    type: tarball
    path_in_archive: 'models_eynollah'
    size: 1889719626
```
…then this is what I get…
```
06:59:37.278 ERROR ocrd.resource_manager - [ocrd-eynollah-segment.0.name] datetime.date(2022, 4, 5) is not of type 'string'
```

I have to prefix the name with some other string to get it working.
